Entregable3/urls.py
from django.urls import path
from Entregable3 import views

app_name = 'Entregable3'

urlpatterns = [

    path('', views.index, name='index'),

]

Medico/urls.py
from django.urls import path
from Medico import views

app_name = 'medico'

urlpatterns = [

    path('', views.index, name='index'),
    path('nuevo/', views.new_medico, name='new_medico'),

    # path('medicos/', views.medicos),
    # path('new_medico/', views.new_medico),
    # path('listar_medicos/', views.listar_medicos),
]

Paciente/urls.py
# paciente/urls.py

from django.urls import path
from Paciente import views

app_name = 'paciente'

urlpatterns = [

    path('', views.index, name='index'),
    path('new_paciente/', views.new_paciente, name='new_paciente'),
    path('buscar_paciente/', views.buscar_paciente, name='buscar_paciente'),
    path('buscar_paciente_resultado/', views.buscar_paciente_resultado, name='buscar_paciente_resultado'),

]

Proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('Entregable3.urls')),

    path('pacientes/', include('Paciente.urls')),

    path('medicos/', include('Medico.urls')),

    path('turnos/', include('Turno.urls')),

]

Turno/urls.py
# turno/urls.py

from django.urls import path
from Turno import views

app_name = 'turno'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('new_turno/', views.new_turno, name='new_turno'),
    
]

Entregable3/models.py
from django.db import models

# Los modelos seran, paciente, medico y turno
    
# class Turno(models.Model):
#     paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
#     medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
#     fecha = models.DateField()
#     hora = models.TimeField()

    # def __str__(self):
    #     return self.paciente.nombre + " " + self.paciente.apellido + " - " + self.medico.nombre + " " + self.medico.apellido + " - " + str(self.fecha) + " - " + str(self.hora)

Medico/models.py
from django.db import models

class Medico(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    matricula = models.CharField(max_length=50, unique=True)    # la matrícula debe ser única

    def __str__(self):
        return self.nombre + " " + self.apellido

Paciente/models.py
# paciente/models.py

from django.db import models


class Paciente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    correo = models.EmailField(unique=True) # el correo debe ser único

    def __str__(self):
        return self.nombre + " " + self.apellido

Proyecto1/models.py
from django.db import models

# Los modelos seran, paciente, medico y turno

class Paciente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    correo = models.EmailField()

    def __str__(self):
        return self.nombre + " " + self.apellido
    
class Medico(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    matricula = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre + " " + self.apellido
    
class Turno(models.Model):
    mailPaciente = models.EmailField()
    matriculaMedico = models.CharField(max_length=50)
    fecha = models.DateField()
    hora = models.TimeField()

    def __str__(self):
        return f'{self.mailPaciente} - {self.matriculaMedico} - {self.fecha} - {self.hora}'

Turno/models.py
from django.db import models

# Turno tiene el mail de un paciente, la matricula de un médico, la fecha y hora del turno

class Turno(models.Model):
    mailPaciente = models.EmailField()
    matriculaMedico = models.IntegerField()
    fecha = models.DateField()
    hora = models.TimeField()

    def __str__(self):
        return f'{self.mailPaciente} - {self.matriculaMedico} - {self.fecha} - {self.hora}'

Medico/forms.py
from django import forms
from .models import Medico

class MedicoForm(forms.ModelForm):
    class Meta:
        model = Medico
        fields = ['nombre', 'apellido', 'matricula']

Paciente/forms.py
# paciente/forms.py

from django import forms
from .models import Paciente

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['nombre', 'apellido', 'correo']

Turno/forms.py
# turno/forms

from django import forms
from .models import Turno

class TurnoForm(forms.ModelForm):
    class Meta:
        model = Turno
        fields = ['mailPaciente', 'matriculaMedico', 'fecha', 'hora']

Entregable3/views.py
from django.http import HttpResponse
from django.template import Template, Context, loader

def index(request):
    
    plantilla = loader.get_template("Entregable3/index.html")

    documento = plantilla.render()

    return HttpResponse(documento)

Medico/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Medico
from .forms import MedicoForm

def index(request):
    medicos = Medico.objects.all()
    contexto = {
        'medicos': medicos
    }

    plantilla = loader.get_template("Medico/index.html")
    documento = plantilla.render(contexto, request)

    return HttpResponse(documento)

def new_medico(request):
    if request.method == 'POST':
        form = MedicoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('medico:index')
    else:
        form = MedicoForm()

    contexto = {
        'form': form
    }

    return render(request, 'Medico/new_medico.html', contexto)

Paciente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Paciente
from .forms import PacienteForm

def index(request):
    pacientes = Paciente.objects.all()
    contexto = {
        'pacientes': pacientes
    }

    plantilla = loader.get_template("Paciente/index.html")
    documento = plantilla.render(contexto, request)

    return HttpResponse(documento)

def new_paciente(request):
    if request.method == 'POST':
        form = PacienteForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('paciente:index')
    else:
        form = PacienteForm()

    return render(request, 'Paciente/new_paciente.html', {'form': form})

def buscar_paciente(request):

    return render(request, 'Paciente/buscar_paciente.html')

def buscar_paciente_resultado(request):
    if request.GET["nombre"]:
        nombre = request.GET["nombre"]
        pacientes = Paciente.objects.filter(nombre=request.GET["nombre"].capitalize())  # Pongo el nombre en mayusculas para que no haya problemas con la busqueda (si el nombre esta en la base de datos en minusculas y el usuario lo introduce en mayusculas no lo encontrara

        return render(request, 'Paciente/buscar_paciente_resultado.html', {'pacientes': pacientes})
    
    else:
        respuesta = "No has introducido ningun nombre"

    return HttpResponse(respuesta)

Turno/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Turno
from .forms import TurnoForm

def index(request):
    turnos = Turno.objects.all()
    contexto = {
        'turnos': turnos
    }

    plantilla = loader.get_template("Turno/index.html")
    documento = plantilla.render(contexto, request)

    return HttpResponse(documento)

def new_turno(request):
    if request.method == 'POST':
        form = TurnoForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('turno:index')
    else:
        form = TurnoForm()

    return render(request, 'Turno/new_turno.html', {'form': form})

Entregable3/templates/Entregable3/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="keywords" content="your, keywords, here" />
    </head>
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
 
            {% endblock title %}
        </title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'Entregable3/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
              rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Entregable3/css/styles.css' %}" rel="stylesheet" />
    </head>

    <body>

        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="#!">Hospital</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link "
                               aria-current="page"
                               href="{% url 'Entregable3:index' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'paciente:index' %}">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'medico:index' %}">Medicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'turno:index' %}">Turnos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Entregable3/js/scripts.js' %}"></script>
        {% block content %}
 
        {% endblock content %}
    </body>

    <!--<footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">
                Copyright &copy; Your Website 2023
            </p>
        </div>
    </footer>-->
</html>

Entregable3/templates/Entregable3/index.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Hospital
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
        <title>Hospital</title>
    </head>
    <body>
        {% block content %}

            <!-- Responsive navbar-->
            <!-- Header-->
            <header class="py-5">
                <div class="container px-lg-5">
                    <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                        <div class="m-4 m-lg-5">
                            <h2 class="fw-bold">Bienvenido al sistema de gestión del Hospital!</h2>
                            <br />
                            <p class="fs-5">
                                Aqui podrá gestionar los medicos y pacientes del hospital, asi como tambien configurar citas medicas.
                            </p>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Page Content-->
            <section class="pt-4">
                <div class="container px-lg-5">
                    <!-- Page Features-->
                    <div class="row gx-lg-5">
                        <div class="col-lg-4 col-xxl-4 mb-5">
                            <div class="card bg-light border-0 h-100">
                                <a href="{% url 'medico:index' %}"
                                   style="text-decoration: none;
                                          color: black">
                                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4">
                                            <i class="bi bi-person-fill"></i>
                                        </div>
                                        <h2 class="fs-4 fw-bold">Gestión de Médicos</h2>
                                        <p class="mb-0">Aqui podrá gestionar los medicos del hospital.</p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-xxl-4 mb-5">
                            <div class="card bg-light border-0 h-100">
                                <a href="{% url 'paciente:index' %}"
                                   style="text-decoration: none;
                                          color: black">
                                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4">
                                            <i class="bi bi-person"></i>
                                        </div>
                                        <h2 class="fs-4 fw-bold">Gestión de Pacientes</h2>
                                        <p class="mb-0">Aqui podrá gestionar los pacientes del hospital.</p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-xxl-4 mb-5">
                            <div class="card bg-light border-0 h-100">
                                <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4">
                                        <i class="bi bi-calendar"></i>
                                    </div>
                                    <h2 class="fs-4 fw-bold">Gestión de turnos</h2>
                                    <p class="mb-0">Aqui podrá gestionar reservar turnos, asociarlos a medicos y pacientes.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Footer-->

        {% endblock content %}
    </body>
</html>

Medico/templates/Medico/index.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Medicos
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
    </head>
    <body>
        <!-- Page content-->
        {% block content %}
            <div class="container mt-5">
                <div class="row">

                    <h2 class=" col-9">Listado de Medicos</h2>
                    <a class="col-3 btn btn-primary" href="{% url 'medico:new_medico' %}">Agregar Medico</a>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Matricula</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for medico in medicos %}
                                <tr>
                                    <td>{{ medico.nombre }}</td>
                                    <td>{{ medico.apellido }}</td>
                                    <td>{{ medico.matricula }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

    {% endblock content %}
</body>
</html>

Medico/templates/Medico/new_medico.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}


<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block title %}
            Agregar medico
        {% endblock title %}

    </head>
    <body>
        <!-- Page content-->
        {% block content %}
            <div class="container mt-5">
                <div class="row">
                    <div class="col-md-6 offset-md-3 container">
                        <div class="container rounded-5" style="background-color: #ced4da">
                            <h2 class="text-center pt-4">Registrar Medico</h2>
                            <form method="post" class="mb-4 p-4">
                                {% csrf_token %}
                                {{ form }}
                                <br />
                                <a class="btn btn-secondary" href="{% url "medico:index" %}">Volver</a>
                                <button type="submit" class="btn btn-primary">Registrar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endblock content %}
    </body>
</html>

Paciente/templates/Paciente/buscar_paciente.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Buscar Paciente
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
    </head>
    <body>

        {% block content %}

            <div style="display: flex;
                        justify-content: center;
                        align-items: center;
                        height: 100vh">
                <div style="background-color: #f8f9fa; border-radius: 10px; padding: 20px">
                    <form action="{% url 'paciente:buscar_paciente_resultado' %}" method="GET">
                        {% csrf_token %}
                        <label for="nombre">Nombre:</label>
                        <input type="text" id="nombre" name="nombre" required />
                        <button type="submit">Buscar</button>
                    </form>
                </div>
            </div>

            <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

        {% endblock content %}

    </body>
</html>

Paciente/templates/Paciente/buscar_paciente_resultado.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Buscar Paciente
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css"
              rel="stylesheet" />
    </head>
    <body>

        {% block content %}

            <div class="container mt-5">
                <div class="d-flex justify-content-center align-items-center"
                     style="min-height: 80vh">
                    {% if pacientes %}
                        <div class="row">
                            <h2 class="col-12">Resultado de la búsqueda</h2>
                            <table class="table table-striped mt-3">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>Correo</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for paciente in pacientes %}
                                        <tr>
                                            <td>{{ paciente.nombre }}</td>
                                            <td>{{ paciente.apellido }}</td>
                                            <td>{{ paciente.correo }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <div class="text-center"
                             style="background-color: #f8f9fa;
                                    border-radius: 10px;
                                    padding: 20px">
                            <h1>No se encontraron pacientes</h1>
                        </div>
                    {% endif %}
                </div>
            </div>

        {% endblock content %}

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

    </body>
</html>

Paciente/templates/Paciente/index.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Pacientes
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
        <title>Pacientes</title>
    </head>
    <body>
        <!-- Page content-->
        {% block content %}
            <div class="container mt-5">
                <div class="row mb-4">
                    <div class="col-9">
                        <h2>Listado de Pacientes</h2>
                    </div>
                    <div class="col-3 d-flex justify-content-end align-items-center">
                        <a class="btn btn-primary me-2" href="{% url 'paciente:new_paciente' %}">Agregar Paciente</a>
                        <a class="btn btn-primary btn-circle"
                           href="{% url 'paciente:buscar_paciente' %}">
                            <i class="bi bi-search"></i>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Correo</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for paciente in pacientes %}
                                <tr>
                                    <td>{{ paciente.nombre }}</td>
                                    <td>{{ paciente.apellido }}</td>
                                    <td>{{ paciente.correo }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

        {% endblock content %}
    </body>
</html>

<style>
    .btn-circle {
        width: 40px;
        height: 40px;
        padding: 6px 0;
        border-radius: 50%;
        text-align: center;
        font-size: 18px;
        line-height: 1.42857;
    }
</style>

Paciente/templates/Paciente/new_paciente.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Agregar Paciente
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
    </head>
    <body>

        <!-- Page content-->
        {% block content %}
            <div class="container mt-5">
                <div class="row">
                    <div class="col-md-6 offset-md-3 container">
                        <div class="container rounded-5" style="background-color: #ced4da">
                            <h2 class="text-center pt-4">Registrar Paciente</h2>
                            <form method="post" class="mb-4 p-4">
                                {% csrf_token %}
                                {{ form }}
                                <br />
                                <a href="{% url 'paciente:index' %}" class="btn btn-secondary text-end">Cancelar</a>
                                <button type="submit" class="btn btn-primary text-end">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

        {% endblock content %}
    </body>
</html>

Proyecto1/templates/template1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Soy un template</title>
    </head>
    <body></body>
</html>

Turno/templates/Turno/index.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Turnos
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
        <title>Pacientes</title>
    </head>
    <body>
        <!-- Page content-->
        {% block content %}
            <div class="container mt-5">
                <div class="row">
                    <h2 class="col-9">Listado turnos</h2>
                    <a class="col-3 btn btn-primary" href="{% url 'turno:new_turno' %}">Agregar Turno</a>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Hora</th>
                                <th>Correo</th>
                                <th>Matricula</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for turno in turnos %}
                                <tr>
                                    <td>{{ turno.fecha }}</td>
                                    <td>{{ turno.hora }}</td>
                                    <td>{{ turno.mailPaciente }}</td>
                                    <td>{{ turno.matriculaMedico }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </div>
                </div>

                <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

            {% endblock content %}
        </body>
    </html>

Turno/templates/Turno/new_turno.html
<!DOCTYPE html>

{% extends "Entregable3/base.html" %}
{% block title %}
    Agregar Paciente
{% endblock title %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Your meta description goes here" />
        <meta name="keywords" content="your, meta, keywords, go, here" />
    </head>
    <body>

        <!-- Page content-->
        {% block content %}
            <div class="container mt-5">
                <div class="row">
                    <div class="col-md-6 offset-md-3 container">
                        <div class="container rounded-5" style="background-color: #ced4da">
                            <h2 class="text-center pt-4">Registrar Paciente</h2>
                            <form method="post" class="mb-4 p-4">
                                {% csrf_token %}
                                {{ form }}
                                <br />
                                <a href="{% url 'paciente:index' %}" class="btn btn-secondary text-end">Cancelar</a>
                                <button type="submit" class="btn btn-primary text-end">Registrar</button>
                            </form>
                            <br />
                            <p class="text-center">
                                Recuerde que puede ver los correos de los pacientes y las matriculas de los medicos en la lista de pacientes y medicos respectivamente.
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>

            <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

        {% endblock content %}
    </body>
</html>